name: Pages

on:
  push:
    branches:
      - main

jobs:
  release-unstable:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Build Pages
        run: npm run build:pages

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
